/**
 * Mock backend for the frontend: seeded vendors, bookings, chats, offers,
 * notifications and reports, persisted to localStorage under STORAGE_KEY.
 * `loadSavedState()` hydrates on boot (falling back to the seeds below);
 * `saveState()` writes back on every store change. The demo role-switcher
 * swaps `currentUser` between the three persona accounts defined here.
 */
import type {
  UserProfile,
  VendorItem,
  BookingItem,
  Conversation,
  OfferItem,
  NotificationItem,
  ReportItem,
} from "../types";

const STORAGE_KEY = "ccm_mvp_v12_state";

export interface MarketplaceState {
  currentUser: UserProfile;
  activeRole: "customer" | "vendor" | "admin";
  vendors: VendorItem[];
  bookings: BookingItem[];
  conversations: Conversation[];
  offers: OfferItem[];
  notifications: NotificationItem[];
  reports: ReportItem[];
}

export const defaultStudentUser: UserProfile = {
  id: "firebase_usr_aarav_987",
  name: "Aarav Mehta",
  email: "aarav.mehta@campus.edu",
  phone: "+91 98765 43210",
  hostel: "Maple Hostel",
  roomNumber: "B-204",
  role: "CUSTOMER",
  isProfileComplete: true,
  authProvider: "google",
  notificationPreferences: {
    serviceUpdatesInApp: true,
    serviceUpdatesEmail: false,
    promoInApp: true,
  },
};

export const defaultPilotVendorUser: UserProfile = {
  id: "firebase_usr_rahul_freshfold",
  name: "Rahul Verma",
  email: "rahul@freshfold.in",
  phone: "+91 98222 33445",
  hostel: "Vendor Annex",
  roomNumber: "V-12",
  role: "VENDOR_OWNER",
  isProfileComplete: true,
  authProvider: "google",
  vendorId: "fresh-fold",
  vendorName: "FreshFold Laundry",
};

export const defaultAdminUser: UserProfile = {
  id: "firebase_usr_admin_master",
  name: "System Admin",
  email: "admin@campuscommerce.in",
  phone: "+91 98000 00000",
  hostel: "Administration Center",
  roomNumber: "Room 101",
  role: "ADMIN",
  isProfileComplete: true,
  authProvider: "firebase",
};

export const initialVendors: VendorItem[] = [
  {
    id: "fresh-fold",
    name: "FreshFold Laundry",
    ownerName: "Rahul Verma",
    email: "rahul@freshfold.in",
    phone: "+91 98222 33445",
    type: "Campus Laundry Partner",
    category: "laundry",
    description: "Reliable hostel pickup with careful wash, steam iron, and fold service. Serving all campus hostels with 48h turnaround.",
    area: "All campus hostels (Maple, Oak, Pine, Rose)",
    status: "Available now",
    price: "₹80/kg + ₹30 fee",
    color: "lilac",
    mark: "FF",
    offer: "Weekend Wash Deal: ₹60/kg",
    tags: ["Pilot Business", "Hostel Pickup", "Bargaining Allowed", "Steam Iron", "48h Return"],
    services: ["Wash + Iron", "Wash Only", "Iron Only"],
    verified: true,
    rating: 4.9,
    operatingHours: "8:00 AM – 8:30 PM",
    serviceArea: "All campus student hostels",
    negotiationEnabled: true,
    accessStatus: "ACTIVE",
    accessStart: "2025-01-01",
    accessEnd: "2026-12-31",
    plan: "PAID",
    monthlyPrice: 1500,
    isPilotBusiness: true,
    allowedClothing: ["Shirt", "T-Shirt", "Pant", "Shorts", "Bedsheet", "Towel"],
    restrictedClothing: ["Underwear (Not accepted)", "Heavy Blankets (Dry clean only)"],
    serviceTypes: [
      { name: "Wash + Iron", pricePerKg: 80, serviceFee: 30 },
      { name: "Wash Only", pricePerKg: 60, serviceFee: 20 },
      { name: "Iron Only", pricePerKg: 40, serviceFee: 15 },
    ],
  },
  {
    id: "campus-wheels",
    name: "Campus Wheels",
    ownerName: "Amit Singh",
    email: "amit@campuswheels.in",
    phone: "+91 98333 44556",
    type: "Campus Bike Rides",
    category: "ride",
    description: "Safe, rapid campus bike transit between designated points. Verified student riders, locked fare matrix.",
    area: "6 predefined campus points",
    status: "Riders on duty",
    price: "₹40 – ₹60 matrix fare",
    color: "sky",
    mark: "CW",
    offer: "Flat ₹40 to Main Gate",
    tags: ["Strict Max 2 Pax", "Fixed Fare Matrix", "Verified Riders", "No Bargaining"],
    services: ["Bike Ride"],
    verified: true,
    rating: 4.8,
    operatingHours: "7:00 AM – 10:30 PM",
    serviceArea: "Campus boundary & designated gates",
    negotiationEnabled: false, // PRD Section 20: Bike fare calculated from fare matrix, NO negotiation
    accessStatus: "ACTIVE",
    accessStart: "2025-01-01",
    accessEnd: "2026-12-31",
    plan: "PAID",
    monthlyPrice: 1500,
    fareMatrix: {
      "Main Gate": {
        "Maple Hostel": { 1: 40, 2: 60 },
        "Hostel A": { 1: 40, 2: 60 },
        "Hostel B": { 1: 40, 2: 60 },
        "Academic Block": { 1: 30, 2: 50 },
        "Library": { 1: 35, 2: 55 },
        "Market Area": { 1: 45, 2: 65 },
      },
      "Academic Block": {
        "Main Gate": { 1: 30, 2: 50 },
        "Maple Hostel": { 1: 35, 2: 55 },
        "Hostel A": { 1: 35, 2: 55 },
        "Hostel B": { 1: 35, 2: 55 },
        "Library": { 1: 25, 2: 40 },
        "Market Area": { 1: 40, 2: 60 },
      },
      "Library": {
        "Main Gate": { 1: 35, 2: 55 },
        "Maple Hostel": { 1: 30, 2: 50 },
        "Academic Block": { 1: 25, 2: 40 },
        "Hostel A": { 1: 30, 2: 50 },
        "Hostel B": { 1: 30, 2: 50 },
        "Market Area": { 1: 35, 2: 55 },
      },
    },
    riders: [
      { id: "rd-1", name: "Rohan Das", phone: "+91 98765 00123", vehicleIdentifier: "Activa DL-04-204", active: true },
      { id: "rd-2", name: "Vikrant Sen", phone: "+91 98765 00124", vehicleIdentifier: "Splendor DL-09-551", active: true },
    ],
  },
  {
    id: "green-bowl",
    name: "Green Bowl",
    ownerName: "Nisha Kapoor",
    email: "nisha@greenbowl.in",
    phone: "+91 98111 22334",
    type: "Wholesome Campus Kitchen",
    category: "food",
    description: "Fresh wholesome vegetarian bowls, wraps, and comforting campus favourites prepared daily inside north campus.",
    area: "North & South Hostels",
    status: "Kitchen open",
    price: "Bowls from ₹70",
    color: "sage",
    mark: "GB",
    offer: "15% off lunch bowls",
    tags: ["Veg-only", "Fresh Daily", "Hostel Gate Delivery", "Negotiable on Bulk"],
    services: ["Browse Menu", "Meal Subscriptions"],
    verified: true,
    rating: 4.7,
    operatingHours: "11:00 AM – 9:45 PM",
    serviceArea: "Maple Hostel, Hostel A, Hostel B, Library",
    dietaryClassification: "VEG_ONLY",
    minimumOrder: 70,
    negotiationEnabled: true,
    accessStatus: "ACTIVE",
    accessStart: "2025-01-01",
    accessEnd: "2026-12-31",
    plan: "PAID",
    monthlyPrice: 1500,
    deliveryBoundaries: ["Maple Hostel Gate", "Hostel A Gate", "Campus Main Gate", "Collection Counter"],
    menuItems: [
      { id: "m-1", name: "Paneer Rice Bowl", price: 90, category: "Bowls", dietary: "VEG", description: "Grilled paneer, fragrant jeera rice, greens and house mint chutney.", color: "meal-one", available: true },
      { id: "m-2", name: "Garden Wrap", price: 70, category: "Wraps", dietary: "VEG", description: "Crunchy seasonal vegetables, garlic hummus, and roasted wrap.", color: "meal-two", available: true },
      { id: "m-3", name: "Masala Khichdi", price: 80, category: "Bowls", dietary: "VEG", description: "Comforting moong dal rice with seasonal vegetables & desi ghee.", color: "meal-three", available: true },
      { id: "m-4", name: "Cold Coffee", price: 50, category: "Beverages", dietary: "VEG", description: "Rich creamy cold coffee brewed fresh with chocolate drizzle.", color: "meal-one", available: true },
    ],
  },
  {
    id: "campus-grill",
    name: "Campus Grill & Tiffin",
    ownerName: "Arjun Nair",
    email: "arjun@campusgrill.in",
    phone: "+91 98444 55667",
    type: "Campus Diner & Tiffin",
    category: "food",
    description: "Homestyle egg curry thalis, chicken rolls, and paneer platters for late night campus cravings.",
    area: "Campus Market Area & Gates",
    status: "Kitchen open",
    price: "Meals from ₹85",
    color: "orange",
    mark: "CG",
    offer: "Free beverage with 2 rolls",
    tags: ["Veg & Non-Veg", "Late Night", "Campus Gate Pickup"],
    services: ["Browse Menu"],
    verified: true,
    rating: 4.6,
    operatingHours: "12:00 PM – 11:30 PM",
    serviceArea: "All campus hostel gates & market",
    dietaryClassification: "VEG_AND_NON_VEG",
    minimumOrder: 85,
    negotiationEnabled: false,
    accessStatus: "ACTIVE",
    accessStart: "2025-02-01",
    accessEnd: "2026-12-31",
    plan: "PAID",
    monthlyPrice: 1500,
    deliveryBoundaries: ["Campus Gate 1", "Hostel Reception", "Market Counter"],
    menuItems: [
      { id: "cg-1", name: "Egg Curry with Rice", price: 110, category: "Meals", dietary: "NON_VEG", description: "Double egg spiced gravy with steamed basmati rice and pickle.", color: "meal-one", available: true },
      { id: "cg-2", name: "Smoked Chicken Roll", price: 120, category: "Rolls", dietary: "NON_VEG", description: "Tandoori chicken pieces wrapped in flaky paratha with sliced onions.", color: "meal-two", available: true },
      { id: "cg-3", name: "Paneer Tikka Roll", price: 95, category: "Rolls", dietary: "VEG", description: "Marinated cottage cheese with bell peppers and green chutney.", color: "meal-three", available: true },
    ],
  },
];

export const initialConversations: Conversation[] = [
  {
    id: "conv-pilot-freshfold",
    bookingId: "CCM-L-1042",
    customerId: "firebase_usr_aarav_987",
    customerName: "Aarav Mehta",
    vendorId: "fresh-fold",
    vendorName: "FreshFold Laundry",
    serviceType: "laundry",
    serviceTitle: "Wash + Iron (2.1 kg estimate)",
    listedPrice: "₹198 (₹80/kg + ₹30 fee)",
    agreedPrice: 175,
    negotiationStatus: "AGREED",
    currentOffer: null,
    updatedAt: "10 mins ago",
    messages: [
      {
        id: "msg-1",
        conversationId: "conv-pilot-freshfold",
        senderId: "firebase_usr_aarav_987",
        senderRole: "customer",
        senderName: "Aarav Mehta",
        timestamp: "10:14 AM",
        type: "TEXT",
        content: "Hi Rahul bhaiya! Can you pick up 3 shirts, 2 pants, and 1 bedsheet from Maple Hostel B-204 today?",
      },
      {
        id: "msg-2",
        conversationId: "conv-pilot-freshfold",
        senderId: "firebase_usr_rahul_freshfold",
        senderRole: "vendor",
        senderName: "Rahul Verma (FreshFold)",
        timestamp: "10:16 AM",
        type: "TEXT",
        content: "Yes Aarav! Our boy will be at Maple Hostel at 1:30 PM. Please leave the bag with reception or room.",
      },
      {
        id: "msg-3",
        conversationId: "conv-pilot-freshfold",
        senderId: "firebase_usr_aarav_987",
        senderRole: "customer",
        senderName: "Aarav Mehta",
        timestamp: "10:18 AM",
        type: "OFFER",
        content: "Awesome. Listed is ₹198, could you do ₹160 for regular campus student?",
        offerAmount: 160,
      },
      {
        id: "msg-4",
        conversationId: "conv-pilot-freshfold",
        senderId: "firebase_usr_rahul_freshfold",
        senderRole: "vendor",
        senderName: "Rahul Verma (FreshFold)",
        timestamp: "10:20 AM",
        type: "COUNTER_OFFER",
        content: "I can give you campus loyalty discount: ₹175 total with steam iron included.",
        offerAmount: 175,
      },
      {
        id: "msg-5",
        conversationId: "conv-pilot-freshfold",
        senderId: "firebase_usr_aarav_987",
        senderRole: "customer",
        senderName: "Aarav Mehta",
        timestamp: "10:21 AM",
        type: "OFFER_ACCEPTED",
        content: "Deal! Accepted ₹175. I'll pay in cash/UPI directly at delivery.",
        offerAmount: 175,
      },
      {
        id: "msg-6",
        conversationId: "conv-pilot-freshfold",
        senderId: "system",
        senderRole: "system",
        senderName: "System",
        timestamp: "10:22 AM",
        type: "SYSTEM_STATUS",
        content: "Agreed Price locked at ₹175. Booking CCM-L-1042 updated.",
      },
    ],
  },
  {
    id: "conv-greenbowl-order",
    bookingId: "CCM-F-1042",
    customerId: "firebase_usr_aarav_987",
    customerName: "Aarav Mehta",
    vendorId: "green-bowl",
    vendorName: "Green Bowl",
    serviceType: "food",
    serviceTitle: "2× Paneer Rice Bowl",
    listedPrice: "₹180",
    agreedPrice: null,
    negotiationStatus: "NONE",
    currentOffer: null,
    updatedAt: "25 mins ago",
    messages: [
      {
        id: "msg-gb-1",
        conversationId: "conv-greenbowl-order",
        senderId: "firebase_usr_aarav_987",
        senderRole: "customer",
        senderName: "Aarav Mehta",
        timestamp: "1:05 PM",
        type: "TEXT",
        content: "Hi Nisha ji, please pack extra mint chutney with the paneer rice bowls.",
      },
      {
        id: "msg-gb-2",
        conversationId: "conv-greenbowl-order",
        senderId: "firebase_usr_nisha_greenbowl",
        senderRole: "vendor",
        senderName: "Nisha Kapoor (Green Bowl)",
        timestamp: "1:08 PM",
        type: "TEXT",
        content: "Noted Aarav! Preparing fresh now. Handover will be at Maple Hostel Gate in 20 mins.",
      },
    ],
  },
];

export const initialBookings: BookingItem[] = [
  {
    id: "CCM-L-1042",
    customerId: "firebase_usr_aarav_987",
    customerName: "Aarav Mehta",
    customerPhone: "+91 98765 43210",
    hostel: "Maple Hostel",
    roomNumber: "B-204",
    vendorId: "fresh-fold",
    vendorName: "FreshFold Laundry",
    category: "laundry",
    title: "Wash + Iron (Pilot Laundry)",
    summary: "3 shirts, 2 pants, 1 bedsheet · Bag photo attached",
    status: "PROCESSING",
    listedPrice: "₹198",
    agreedPrice: "₹175 (Negotiated)",
    finalPrice: "₹175",
    paymentNotice: "Payment is collected directly by FreshFold upon return.",
    date: "Today, 10:15 AM",
    time: "10:15 AM",
    conversationId: "conv-pilot-freshfold",
    statusHistory: [
      { status: "REQUESTED", changedAt: "10:15 AM", changedBy: "Aarav Mehta", note: "Booking submitted via app" },
      { status: "ACCEPTED", changedAt: "10:22 AM", changedBy: "Rahul Verma", note: "Negotiated price ₹175 agreed" },
      { status: "RECEIVED", changedAt: "11:00 AM", changedBy: "Rahul Verma", note: "Bag picked up from Maple B-204" },
      { status: "PROCESSING", changedAt: "11:45 AM", changedBy: "Rahul Verma", note: "Wash cycle in progress" },
    ],
    createdAt: new Date(Date.now() - 3600000 * 3).toISOString(),
    bookingData: {
      serviceType: "Wash + Iron",
      quantities: { Shirt: 3, Pant: 2, Bedsheet: 1 },
      weightKg: 2.1,
      bagPhoto: true,
      pickupHostel: "Maple Hostel (Locked)",
      pickupRoom: "B-204",
    },
  },
  {
    id: "CCM-R-1042",
    customerId: "firebase_usr_aarav_987",
    customerName: "Aarav Mehta",
    customerPhone: "+91 98765 43210",
    hostel: "Maple Hostel",
    roomNumber: "B-204",
    vendorId: "campus-wheels",
    vendorName: "Campus Wheels",
    category: "ride",
    title: "Campus Bike Ride",
    summary: "Main Gate → Maple Hostel (1 passenger)",
    status: "ASSIGNED",
    listedPrice: "₹40",
    finalPrice: "₹40",
    paymentNotice: "Payment is collected directly by the rider.",
    date: "Today, 12:30 PM",
    time: "12:30 PM",
    rider: {
      id: "rd-1",
      name: "Rohan Das",
      phone: "+91 98765 00123",
      vehicleIdentifier: "Activa DL-04-204",
      active: true,
    },
    statusHistory: [
      { status: "REQUESTED", changedAt: "12:30 PM", changedBy: "Aarav Mehta", note: "Ride requested" },
      { status: "ASSIGNED", changedAt: "12:32 PM", changedBy: "Amit Singh", note: "Rider Rohan Das assigned" },
    ],
    createdAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    bookingData: {
      pickup: "Main Gate",
      dropoff: "Maple Hostel",
      passengers: 1,
      scheduledTime: "12:30 PM",
    },
  },
  {
    id: "CCM-F-1042",
    customerId: "firebase_usr_aarav_987",
    customerName: "Aarav Mehta",
    customerPhone: "+91 98765 43210",
    hostel: "Maple Hostel",
    roomNumber: "B-204",
    vendorId: "green-bowl",
    vendorName: "Green Bowl",
    category: "food",
    title: "Vegetarian Lunch Order",
    summary: "2× Paneer Rice Bowl · Extra mint chutney",
    status: "PREPARING",
    listedPrice: "₹180",
    finalPrice: "₹180",
    paymentNotice: "Payment is collected directly at delivery counter.",
    date: "Today, 1:15 PM",
    time: "1:15 PM",
    conversationId: "conv-greenbowl-order",
    statusHistory: [
      { status: "RECEIVED", changedAt: "1:15 PM", changedBy: "Aarav Mehta", note: "Order placed" },
      { status: "ACCEPTED", changedAt: "1:18 PM", changedBy: "Nisha Kapoor", note: "Kitchen accepted" },
      { status: "PREPARING", changedAt: "1:20 PM", changedBy: "Nisha Kapoor", note: "Fresh cooking underway" },
    ],
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    bookingData: {
      items: [{ name: "Paneer Rice Bowl", quantity: 2, price: 90 }],
      collectionPoint: "Maple Hostel Gate",
      dietary: "VEG_ONLY",
    },
  },
];

export const initialOffers: OfferItem[] = [
  {
    id: "off-pilot-weekend",
    vendorId: "fresh-fold",
    vendorName: "FreshFold Laundry",
    title: "Weekend Laundry Special",
    description: "Wash + Steam Iron package for regular clothes. Free pickup from all student hostels.",
    applicableItem: "Wash + Steam Iron (Min 3 kg)",
    originalPrice: 80,
    offerPrice: 60,
    startAt: "2025-06-01T00:00",
    endAt: "2026-12-31T23:59",
    validity: "Friday → Sunday",
    eligibility: "All registered campus students",
    location: "All Hostels",
    published: true,
  },
  {
    id: "off-greenbowl-lunch",
    vendorId: "green-bowl",
    vendorName: "Green Bowl",
    title: "Lunch Bowl Discount",
    description: "Get 15% off any paneer or khichdi rice bowl during peak lunch hours.",
    applicableItem: "Paneer Rice Bowl",
    originalPrice: 90,
    offerPrice: 75,
    startAt: "2025-06-01T12:00",
    endAt: "2026-12-31T15:00",
    validity: "Daily 12:00 PM – 3:00 PM",
    eligibility: "Campus ID card holders",
    location: "North Campus Hostels",
    published: true,
  },
  {
    id: "off-wheels-flat",
    vendorId: "campus-wheels",
    vendorName: "Campus Wheels",
    title: "Morning Academic Express",
    description: "Flat rate rides between hostels and the Academic Block before 9:00 AM.",
    applicableItem: "Single passenger ride",
    originalPrice: 40,
    offerPrice: 30,
    startAt: "2025-06-01T07:00",
    endAt: "2026-12-31T09:00",
    validity: "Monday → Friday 7–9 AM",
    eligibility: "All campus students",
    location: "Hostels → Academic Block",
    published: true,
  },
];

export const initialNotifications: NotificationItem[] = [
  {
    id: "notif-1",
    userId: "firebase_usr_aarav_987",
    title: "Laundry Status Update",
    message: "FreshFold marked CCM-L-1042 as PROCESSING. Wash cycle in progress.",
    timestamp: "15 min ago",
    read: false,
    category: "booking",
    targetType: "booking",
    targetId: "CCM-L-1042",
  },
  {
    id: "notif-2",
    userId: "firebase_usr_aarav_987",
    title: "Rider Assigned",
    message: "Rohan Das (Activa DL-04-204) has been assigned to your ride request CCM-R-1042.",
    timestamp: "45 min ago",
    read: false,
    category: "booking",
    targetType: "booking",
    targetId: "CCM-R-1042",
  },
  {
    id: "notif-3",
    userId: "firebase_usr_aarav_987",
    title: "Offer Accepted & Price Locked",
    message: "Rahul Verma accepted your counter-offer of ₹175 for laundry service.",
    timestamp: "2 hr ago",
    read: true,
    category: "chat",
    targetType: "chat",
    targetId: "conv-pilot-freshfold",
  },
];

export const initialReports: ReportItem[] = [
  {
    id: "rep-101",
    reporterId: "firebase_usr_aarav_987",
    reporterName: "Aarav Mehta",
    targetType: "VENDOR",
    targetId: "campus-grill",
    targetName: "Campus Grill & Tiffin",
    reason: "Delayed delivery by 40 minutes without update",
    details: "Ordered dinner at 9:00 PM, arrived at 10:20 PM. Vendor was polite but needs better time updates.",
    status: "RESOLVED",
    createdAt: "Yesterday",
  },
];

export function loadSavedState(): MarketplaceState {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (raw) {
      const parsed = JSON.parse(raw);
      if (parsed.vendors && parsed.bookings && parsed.currentUser) {
        return parsed;
      }
    }
  } catch {
    // fallback
  }
  return {
    currentUser: defaultStudentUser,
    activeRole: "customer",
    vendors: initialVendors,
    bookings: initialBookings,
    conversations: initialConversations,
    offers: initialOffers,
    notifications: initialNotifications,
    reports: initialReports,
  };
}

export function saveState(state: MarketplaceState) {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
  } catch {
    // Ignore storage quota errors
  }
}
